<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the base validation class for response entities.
 */
class SurveyManager_Entity_Validator_Base_Response extends SurveyManager_Validator
{
    /**
     * Performs all validation rules.
     *
     * @return mixed either array with error information or true on success
     */
    public function validateAll()
    {
        $errorInfo = array('message' => '', 'code' => 0, 'debugArray' => array());
        $dom = ZLanguage::getModuleDomain('SurveyManager');
        if (!$this->isStringNotEmpty('workflowState')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('workflow state'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('ipAddress', 40)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('ip address', 40), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('ipAddress')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('ip address'), $dom);
            return $errorInfo;
        }
        if (!$this->isValidInteger('responseTimestamp')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('response timestamp'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('responseTimestamp', 11)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('response timestamp', 11), $dom);
            return $errorInfo;
        }
        if (!$this->isValidBoolean('featured')) {
            $errorInfo['message'] = __f('Error! Field value must be a valid boolean (%s).', array('featured'), $dom);
            return $errorInfo;
        }
    
        return true;
    }
    
    /**
     * Check for unique values.
     *
     * This method determines if there already exist responses with the same response.
     *
     * @param string $fieldName The name of the property to be checked
     * @return boolean result of this check, true if the given response does not already exist
     */
    public function isUniqueValue($fieldName)
    {
        if ($this->entity[$fieldName] === '') {
            return false;
        }
    
        $entityClass = 'SurveyManager_Entity_Response';
        $serviceManager = ServiceUtil::getManager();
        $entityManager = $serviceManager->getService('doctrine.entitymanager');
        $repository = $entityManager->getRepository($entityClass);
    
        $excludeid = $this->entity['id'];
    
        return $repository->detectUniqueState($fieldName, $this->entity[$fieldName], $excludeid);
    }
    
    /**
     * Get entity.
     *
     * @return Zikula_EntityAccess
     */
    public function getEntity()
    {
        return $this->entity;
    }
    
    /**
     * Set entity.
     *
     * @param Zikula_EntityAccess $entity.
     *
     * @return void
     */
    public function setEntity(Zikula_EntityAccess $entity = null)
    {
        $this->entity = $entity;
    }
    
}
