<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the base validation class for survey entities.
 */
class SurveyManager_Entity_Validator_Base_Survey extends SurveyManager_Validator
{
    /**
     * Performs all validation rules.
     *
     * @return mixed either array with error information or true on success
     */
    public function validateAll()
    {
        $errorInfo = array('message' => '', 'code' => 0, 'debugArray' => array());
        $dom = ZLanguage::getModuleDomain('SurveyManager');
        if (!$this->isStringNotEmpty('workflowState')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('workflow state'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('name', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('name', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('name')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('name'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('description', 5000)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('description', 5000), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('thankYou', 2000)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('thank you', 2000), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('thankYouTitle', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('thank you title', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('thankYouAlternativeUrl', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('thank you alternative url', 255), $dom);
            return $errorInfo;
        }
        if ($this->entity['thankYouAlternativeUrl'] != '' && !$this->isValidUrl('thankYouAlternativeUrl')) {
            $errorInfo['message'] = __f('Error! Field value must be a valid url (%s).', array('thank you alternative url'), $dom);
            return $errorInfo;
        }
        if (!$this->isValidInteger('weight')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('weight'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('weight', 11)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('weight', 11), $dom);
            return $errorInfo;
        }
        if (!$this->isValidInteger('maxPerIp')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('max per ip'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('maxPerIp', 4)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('max per ip', 4), $dom);
            return $errorInfo;
        }
        if (!$this->isValidInteger('maxPerUserId')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('max per user id'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('maxPerUserId', 4)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('max per user id', 4), $dom);
            return $errorInfo;
        }
        if (!$this->isValidBoolean('useCaptcha')) {
            $errorInfo['message'] = __f('Error! Field value must be a valid boolean (%s).', array('use captcha'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('responseSubject', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('response subject', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('confirmationSubject', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('confirmation subject', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('confirmationBody', 2000)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('confirmation body', 2000), $dom);
            return $errorInfo;
        }
        if (!$this->isValidBoolean('archived')) {
            $errorInfo['message'] = __f('Error! Field value must be a valid boolean (%s).', array('archived'), $dom);
            return $errorInfo;
        }
        if (!$this->isValidBoolean('template')) {
            $errorInfo['message'] = __f('Error! Field value must be a valid boolean (%s).', array('template'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('addition1', 100)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('addition1', 100), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('addition2', 100)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('addition2', 100), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('addition3', 100)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('addition3', 100), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('addition4', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('addition4', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('addition5', 2000)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('addition5', 2000), $dom);
            return $errorInfo;
        }
    
        return true;
    }
    
    /**
     * Check for unique values.
     *
     * This method determines if there already exist surveys with the same survey.
     *
     * @param string $fieldName The name of the property to be checked
     * @return boolean result of this check, true if the given survey does not already exist
     */
    public function isUniqueValue($fieldName)
    {
        if ($this->entity[$fieldName] === '') {
            return false;
        }
    
        $entityClass = 'SurveyManager_Entity_Survey';
        $serviceManager = ServiceUtil::getManager();
        $entityManager = $serviceManager->getService('doctrine.entitymanager');
        $repository = $entityManager->getRepository($entityClass);
    
        $excludeid = $this->entity['id'];
    
        return $repository->detectUniqueState($fieldName, $this->entity[$fieldName], $excludeid);
    }
    
    /**
     * Get entity.
     *
     * @return Zikula_EntityAccess
     */
    public function getEntity()
    {
        return $this->entity;
    }
    
    /**
     * Set entity.
     *
     * @param Zikula_EntityAccess $entity.
     *
     * @return void
     */
    public function setEntity(Zikula_EntityAccess $entity = null)
    {
        $this->entity = $entity;
    }
    
}
