<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * Abstract object selector plugin implementation class.
 */
abstract class SurveyManager_Form_Plugin_AbstractObjectSelector extends SurveyManager_Form_Plugin_Base_AbstractObjectSelector
{
    // feel free to add your customisation here
}
