<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * This is the Admin api helper class.
 */
class SurveyManager_Api_Base_Admin extends Zikula_AbstractApi
{
    /**
     * Returns available admin panel links.
     *
     * @return array Array of admin links.
     */
    public function getlinks()
    {
        $links = array();

        if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_READ)) {
            $links[] = array('url' => ModUtil::url($this->name, 'user', 'main'),
                             'text' => $this->__('Frontend'),
                             'title' => $this->__('Switch to user area.'),
                             'class' => 'z-icon-es-home');
        }

        $controllerHelper = new SurveyManager_Util_Controller($this->serviceManager);
        $utilArgs = array('api' => 'admin', 'action' => 'getlinks');
        $allowedObjectTypes = $controllerHelper->getObjectTypes('api', $utilArgs);

        if (in_array('survey', $allowedObjectTypes)
            && SecurityUtil::checkPermission($this->name . ':Survey:', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'survey')),
                             'text' => $this->__('Surveys'),
                             'title' => $this->__('Survey list'));
        }
        if (in_array('page', $allowedObjectTypes)
            && SecurityUtil::checkPermission($this->name . ':Page:', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'page')),
                             'text' => $this->__('Pages'),
                             'title' => $this->__('Page list'));
        }
        if (in_array('question', $allowedObjectTypes)
            && SecurityUtil::checkPermission($this->name . ':Question:', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'question')),
                             'text' => $this->__('Questions'),
                             'title' => $this->__('Question list'));
        }
        if (in_array('response', $allowedObjectTypes)
            && SecurityUtil::checkPermission($this->name . ':Response:', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'response')),
                             'text' => $this->__('Responses'),
                             'title' => $this->__('Response list'));
        }
        if (in_array('responseData', $allowedObjectTypes)
            && SecurityUtil::checkPermission($this->name . ':ResponseData:', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url($this->name, 'admin', 'view', array('ot' => 'responseData')),
                             'text' => $this->__('Response datas'),
                             'title' => $this->__('Response data list'));
        }
        if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url($this->name, 'admin', 'config'),
                             'text' => $this->__('Configuration'),
                             'title' => $this->__('Manage settings for this application'));
        }

        return $links;
    }
}
