<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * This is the Ajax controller class providing navigation and interaction functionality.
 */
class SurveyManager_Controller_Ajax extends SurveyManager_Controller_Base_Ajax
{
    // feel free to add your own controller methods here
}
