<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Tue Aug 21 20:13:14 CEST 2012.
 */

/**
 * This handler class handles the page events of the Form called by the surveyManager_admin_edit() function.
 * It aims on the page object type.
 */
class SurveyManager_Form_Handler_Admin_Page_Edit extends SurveyManager_Form_Handler_Admin_Page_Base_Edit
{
    /**
     * Get the default redirect url. Required if no returnTo parameter has been supplied.
     * This method is called in handleCommand so we know which command has been performed.
     *
     * @param array  $args List of arguments.
     *
     * @return string The default redirect url.
     */
    protected function getDefaultReturnUrl($args)
    {
        // redirect to the list of pages
        $viewArgs = array('ot' => 'survey');
        $url = ModUtil::url($this->name, 'admin', 'view', $viewArgs);
    
        return $url;
    }

    /**
     * Input data processing called by handleCommand method.
     *
     * @param Zikula_Form_View $view The form view instance.
     * @param array            $args Additional arguments.
     *
     * @return array form data after processing.
     */
    public function fetchInputData(Zikula_Form_View $view, &$args)
    {
        $otherFormData = parent::fetchInputData($view, $args);

        if ($this->mode == 'create') {
            // get treated entity reference from persisted member var
            $entity = $this->entityRef;

            // Find the maximum current weight
            $where = 'tblSurvey.id = \'' . $entity['survey']['id'] . '\'';
            $pages = ModUtil::apiFunc($this->name, 'selection', 'getEntities', array('ot' => 'page', 'where' => $where));

            $maxWeight = -1;
            foreach ($pages as $page) {
                $maxWeight = max($page['weight'], $maxWeight);
            }
            $maxWeight++;
            $entity->setWeight($maxWeight);

            // save updated entity
            $this->entityRef = $entity;
        }
    
        return $otherFormData;
    }
}
