<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * The surveymanagerObjectTypeSelector plugin provides items for a dropdown selector.
 *
 * Available parameters:
 *   - assign: If set, the results are assigned to the corresponding variable instead of printed out.
 *
 * @param  array            $params All attributes passed to this function from the template.
 * @param  Zikula_Form_View $view   Reference to the view object.
 *
 * @return string The output of the plugin.
 */
function smarty_function_surveymanagerObjectTypeSelector($params, $view)
{
    $dom = ZLanguage::getModuleDomain('SurveyManager');
    $result = array();

    $result[] = array('text' => __('Surveys', $dom), 'value' => 'survey');
    $result[] = array('text' => __('Pages', $dom), 'value' => 'page');
    $result[] = array('text' => __('Questions', $dom), 'value' => 'question');
    $result[] = array('text' => __('Responses', $dom), 'value' => 'response');
    $result[] = array('text' => __('Response datas', $dom), 'value' => 'responseData');

    if (array_key_exists('assign', $params)) {
        $view->assign($params['assign'], $result);

        return;
    }

    return $result;
}
