<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Tue Aug 21 20:13:15 CEST 2012.
 */

/**
 * This plugin searches for a certain answer to a certain question type.
 *
 * @param  array            $params  All attributes passed to this function from the template.
 * @param  Zikula_Form_View $view    Reference to the view object.
 *
 * @return string The output of the plugin.
 */
function smarty_function_surveymanagerHasResponseValue($params, $view)
{
    $questionType = $params['questionType'];
    $responses = $params['responses'];
    $useColumn = false;
    $helper = new SurveyManager_Util_Manual(ServiceUtil::getManager());

    foreach ($responses as $k => $response) {
        $questionValue = $responses[$k][$questionType] = $helper->findResponseValue($response['id'], $questionType);
        if (!empty($questionValue)) {
            $useColumn = true;
        }
    }

    if (isset($params['assign'])) {
        $view->assign($params['assign'], $useColumn);
        return;
    }

    return $useColumn;
}
