<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Mon Aug 20 17:56:17 CEST 2012.
 */

/**
 * Installer implementation class.
 */
class SurveyManager_Installer extends SurveyManager_Base_Installer
{
    /**
     * Install the SurveyManager application.
     *
     * @return boolean True on success, or false.
     */
    public function install()
    {
        // first let the parent class perform the general tasks
        $result = parent::install();
        if (!$result) {
            return $result;
        }


        // insert custom example data using workflow
        $action = 'create';
        $workflowHelper = new SurveyManager_Util_Workflow($this->getServiceManager());

        // create a survey
        $survey = new SurveyManager_Entity_Survey();
        $survey->setName($this->__('Contact Us'));
        $survey->setDescription($this->__('Use this survey to contact us'));
        $survey->setThankYou($this->__('Thank you for contacting us. Someone will be in touch with you shortly.'));
        $survey->setRecipients(array(System::getVar('adminmail')));
        $success = $workflowHelper->executeAction($survey, $action);

        // create a page and add it to the survey
        $page = new SurveyManager_Entity_Page();
        $page->setName($this->__('Contact Us'));
        $page->setDescription($this->__('Please fill out the form below to contact us.'));
        $survey->addPages($page); // calls $page->setSurvey($survey)
        $success = $workflowHelper->executeAction($page, $action);

        // create three questions and add them to the page using workflow
        $question1 = new SurveyManager_Entity_Question();
        $question1->setName($this->__('Your name'));
        $question1->setQuestionType('name_id');
        $question1->setRequired(true);
        $page->addQuestions($question1); // calls $question1->setPage($page)
        $success = $workflowHelper->executeAction($question1, $action);

        $question2 = new SurveyManager_Entity_Question();
        $question2->setName($this->__('Your email address'));
        $question2->setQuestionType('email_from');
        $question2->setRequired(true);
        $page->addQuestions($question2); // calls $question2->setPage($page)
        $success = $workflowHelper->executeAction($question2, $action);

        $question3 = new SurveyManager_Entity_Question();
        $question3->setName($this->__('Your message'));
        $question3->setQuestionType('longtext');
        $question3->setRequired(true);
        $page->addQuestions($question3); // calls $question2->setPage($page)
        $success = $workflowHelper->executeAction($question3, $action);

        // save everything
        $this->entityManager->flush();

        $result = true;

        return $result;
    }
}
