<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Tue Aug 28 11:39:20 CEST 2012.
 */

/**
 * Validator class for encapsulating common entity validation methods.
 *
 * This is the concrete validation class with general checks.
 */
class SurveyManager_Validator extends SurveyManager_Base_Validator
{
    /**
     * Checks if string field value has a value other than ''.
     *
     * @param string $fieldName The name of the property to be checked
     * @return boolean result of this check
     */
    public function isStringNotEmpty($fieldName)
    {
        if ($fieldName == 'responseValue') {
            return true;
        }
        return parent::isStringNotEmpty($fieldName);
    }
}
