<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Tue Aug 21 20:13:14 CEST 2012.
 */

/**
 * Question type class for email addresses.
 */
class SurveyManager_QuestionType_EmailAddress extends SurveyManager_AbstractQuestionType
{
    /**
     * Returns the question type code.
     */
    public function getID()
    {
        return 'email';
    }

    /**
     * Returns the question type name.
     */
    public function getName()
    {
        return $this->__('Email address');
    }

    /**
     * Returns the question type category.
     */
    public function getGroup()
    {
        return $this->__('Structured data');
    }

    /**
     * Returns the editing ui component(s).
     */
    public function getEditInput($question, $response, $context = '')
    {
        $questionId = $question['id'];
        $cssClass = $question['required'] ? 'required' : 'standard';
        $output = '<input class="' . $cssClass . ' validate-email" type="text" id="responses_' . $questionId . '" name="responses[' . $questionId . ']" size="' . $this->getTextInputSize($context) . '" value="' . $response . "\" />\n";
        if ($question['required']) {
            $output .= '<p id="advice-required-responses_' . $questionId . '" class="custom-advice" style="display: none">' . $this->__('Please enter a value for this field.') . "</p>\n";
        }
        $output .= '<p id="advice-validate-email-responses_' . $questionId . '" class="custom-advice" style="display: none">' . $this->__('Sorry, that is not a valid email address.') . "</p>\n";
        if ($context == 'block_survey_display') {
            $output .= '<br />';
        }
        return $output;
    }
}
