<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Tue Aug 21 20:13:14 CEST 2012.
 */

/**
 * Question type class for email (from).
 * We inherit from SurveyManager_QuestionType_EmailAddress instead of SurveyManager_AbstractQuestionType
 * in order to share all aspects which are common for both.
 */
class SurveyManager_QuestionType_EmailFrom extends SurveyManager_QuestionType_EmailAddress
{
    /**
     * Returns the question type code.
     */
    public function getID()
    {
        return 'email_from';
    }

    /**
     * Returns the question type name.
     */
    public function getName()
    {
        return $this->__('Email address (From)');
    }

    /**
     * Returns the question type category.
     */
    public function getGroup()
    {
        return $this->__('Structured data');
    }
}
