<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Tue Aug 21 20:13:14 CEST 2012.
 */

/**
 * Question type class for headings.
 */
class SurveyManager_QuestionType_Heading extends SurveyManager_AbstractQuestionType
{
    /**
     * Returns the question type code.
     */
    public function getID()
    {
        return 'heading';
    }

    /**
     * Returns the question type name.
     */
    public function getName()
    {
        return $this->__('Heading');
    }

    /**
     * Returns the question type category.
     */
    public function getGroup()
    {
        return $this->__('Utility');
    }

    /**
     * Returns label or description for editing.
     */
    public function getEditIntro($question, $withDescription = false, $context = '')
    {
        if ($context == 'admin_response_edit') {
            return parent::getEditIntro($question, $withDescription, $context);
        }

        return '<h2>' . $question['name'] . '</h2>';
    }

    /**
     * Returns label or description for editing.
     */
    public function getEditInput($question, $response, $context = '')
    {
        return '<hr />';
    }
}
