<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Tue Aug 21 20:13:14 CEST 2012.
 */

/**
 * Question type class for selection with likert radio buttons.
 */
class SurveyManager_QuestionType_LikertRadio extends SurveyManager_AbstractQuestionType
{
    /**
     * Returns the question type code.
     */
    public function getID()
    {
        return 'likert_radio';
    }

    /**
     * Returns the question type name.
     */
    public function getName()
    {
        return $this->__('Likert (radio buttons)');
    }

    /**
     * Returns the question type category.
     */
    public function getGroup()
    {
        return $this->__('Selection fields');
    }

    /**
     * Returns the editing ui component(s).
     */
    public function getEditInput($question, $response, $context = '')
    {
        if ($context == 'block_survey_display') {
            return ''; /** TODO: was it on purpose in the old module to hide likert style? (maybe because of limited width) */
        }

        $questionId = $question['id'];
        $output = '';

        $numberOfValues = count($question['questionValues']);
        foreach ($question['questionValues'] as $valueKey => $value) {
            /*if ($valueKey == 0) {
                $output .= '<div class="z-floatleft">' . DataUtil::formatForDisplay($value) . "</div>\n";
            } else*/if ($valueKey == $numberOfValues-1) {
                $selection = ($response == $value || $response == '') ? ' checked="checked"' : '';
                $output .= '<div class="z-floatleft z-right" style="width: 200px">' . "\n";
                $output .= '    <input type="radio" id="responses_' . $questionId . '_' . DataUtil::formatForDisplay($valueKey) . '" name="responses[' . $questionId . ']" value="' . DataUtil::formatForDisplay($value) . '"' . $selection . ' /> ' . DataUtil::formatForDisplay($value) . "\n";
                $output .= "</div>\n";
                //$output .= "<br /><br />\n";
            }/* elseif ($valueKey == $numberOfValues-2) {
                $output .= '<div class="z-floatleft">' . DataUtil::formatForDisplay($value) . "</div>\n";
            }*/ else {
                $selection = ($response == $value) ? ' checked="checked"' : '';
                $output .= '<div class="z-floatleft z-center" style="width: 80px">' . "\n";
                $output .= '    ' . DataUtil::formatForDisplay($value) . "<br />\n";
                $output .= '    <input type="radio" id="responses_' . $questionId . '_' . DataUtil::formatForDisplay($valueKey) . '" name="responses[' . $questionId . ']" value="' . DataUtil::formatForDisplay($value) . '"' . $selection . " />\n";
                $output .= "</div>\n";
            }
            /*if ($context == 'block_survey_display') {
                $output .= '<br />';
            }*/
        }
        $output .= "<br class=\"z-clearer\" /><br />\n";
        return $output;
    }
}
