<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Tue Aug 21 20:13:14 CEST 2012.
 */

/**
 * Question type class for short text.
 */
class SurveyManager_QuestionType_ShortText extends SurveyManager_AbstractQuestionType
{
    /**
     * Returns the question type code.
     */
    public function getID()
    {
        return 'shorttext';
    }

    /**
     * Returns the question type name.
     */
    public function getName()
    {
        return $this->__('Short text');
    }

    /**
     * Returns the question type category.
     */
    public function getGroup()
    {
        return $this->__('Text');
    }

    /**
     * Returns the editing ui component(s).
     */
    public function getEditInput($question, $response, $context = '')
    {
        return $this->getEditInputDefault($question, $response, $context);
    }
}
