<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Tue Aug 21 20:13:14 CEST 2012.
 */

/**
 * Question type class for single selection with dropdown lists.
 */
class SurveyManager_QuestionType_SingleSelectionList extends SurveyManager_AbstractQuestionType
{
    /**
     * Returns the question type code.
     */
    public function getID()
    {
        return 'single_selection';
    }

    /**
     * Returns the question type name.
     */
    public function getName()
    {
        return $this->__('Single selection (drop-down)');
    }

    /**
     * Returns the question type category.
     */
    public function getGroup()
    {
        return $this->__('Selection fields');
    }

    /**
     * Returns the editing ui component(s).
     */
    public function getEditInput($question, $response, $context = '')
    {
        $questionId = $question['id'];
        $output = '<select id="responses_' . $questionId . '" name="responses[' . $questionId . ']">' . "\n";
        $selection = ($response == '' || $responses == -1) ? ' selected="selected"' : '';
        $output .= '    <option value="-1"' . $selection . '>' . $this->__('No response') . "</option>\n";
        foreach ($question['questionValues'] as $valueKey => $value) {
            $selection = ($response == $value) ? ' selected="selected"' : '';
            $output .= '    <option value="' . DataUtil::formatForDisplay($value) . '"' . $selection . '>' . DataUtil::formatForDisplay($value) . "</option>\n";
        }
        $output .= "</select>\n";
        if ($context == 'block_survey_display') {
            $output .= '<br />';
        }
        return $output;
    }

    /**
     * Checks for broken dependencies.
     */
    public function validateDependencies($question, $requiredValue, $inputValue)
    {
        $result = true;
        if ($question['questionValues'][$inputValue] != $requiredValue) {
            $result = false;
        }
        return $result;
    }

    /**
     * Nice formatting.
     */
    public function formatValue($question, $value)
    {
        $newValue = $question['questionValues'][$value];
        return $newValue;
    }
}
