<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * Installer base class.
 */
class SurveyManager_Base_Installer extends Zikula_AbstractInstaller
{
    /**
     * Install the SurveyManager application.
     *
     * @return boolean True on success, or false.
     */
    public function install()
    {
        // create all tables from according entity definitions
        try {
            DoctrineHelper::createSchema($this->entityManager, $this->listEntityClasses());
        } catch (\Exception $e) {
            if (System::isDevelopmentMode()) {
                return LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
            }
            $returnMessage = $this->__f('An error was encountered while creating the tables for the %s extension.', array($this->name));
            if (!System::isDevelopmentMode()) {
                $returnMessage .= ' ' . $this->__('Please enable the development mode by editing the /config/config.php file in order to reveal the error details.');
            }
            return LogUtil::registerError($returnMessage);
        }
    
        // set up all our vars with initial values
        $this->setVar('pageSize', 10);
        $this->setVar('useFeaturedResponses', false);
        $this->setVar('submissionRecipients', '');
        $this->setVar('techEmailRecipients', '');
        $this->setVar('maxFileSizeKb', 2048);
        $this->setVar('fileUploadDirectory', '');
        $this->setVar('maxPhotoWidth', 700);
        $this->setVar('maxPhotoHeight', 550);
        $this->setVar('maxThumbWidth', 120);
        $this->setVar('maxThumbHeight', 90);
        $this->setVar('useAddition1', false);
        $this->setVar('useAddition2', false);
        $this->setVar('useAddition3', false);
        $this->setVar('useAddition4', false);
        $this->setVar('useAddition5', false);
    
        $categoryRegistryIdsPerEntity = array();
    
        // create the default data
        $this->createDefaultData($categoryRegistryIdsPerEntity);
    
        // register persistent event handlers
        $this->registerPersistentEventHandlers();
    
        // register hook subscriber bundles
        HookUtil::registerSubscriberBundles($this->version->getHookSubscriberBundles());
        
    
        // initialisation successful
        return true;
    }
    
    /**
     * Upgrade the SurveyManager application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldVersion Version to upgrade from.
     *
     * @return boolean True on success, false otherwise.
     */
    public function upgrade($oldVersion)
    {
    /*
        // Upgrade dependent on old version number
        switch ($oldVersion) {
            case 1.0.0:
                // do something
                // ...
                // update the database schema
                try {
                    DoctrineHelper::updateSchema($this->entityManager, $this->listEntityClasses());
                } catch (\Exception $e) {
                    if (System::isDevelopmentMode()) {
                        return LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
                    }
                    return LogUtil::registerError($this->__f('An error was encountered while updating tables for the %s extension.', array($this->getName())));
                }
        }
    */
    
        // update successful
        return true;
    }
    
    /**
     * Uninstall SurveyManager.
     *
     * @return boolean True on success, false otherwise.
     */
    public function uninstall()
    {
        // delete stored object workflows
        $result = Zikula_Workflow_Util::deleteWorkflowsForModule($this->getName());
        if ($result === false) {
            return LogUtil::registerError($this->__f('An error was encountered while removing stored object workflows for the %s extension.', array($this->getName())));
        }
    
        try {
            DoctrineHelper::dropSchema($this->entityManager, $this->listEntityClasses());
        } catch (\Exception $e) {
            if (System::isDevelopmentMode()) {
                return LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
            }
            return LogUtil::registerError($this->__f('An error was encountered while dropping tables for the %s extension.', array($this->name)));
        }
    
        // unregister persistent event handlers
        EventUtil::unregisterPersistentModuleHandlers($this->name);
    
        // unregister hook subscriber bundles
        HookUtil::unregisterSubscriberBundles($this->version->getHookSubscriberBundles());
        
    
        // remove all module vars
        $this->delVars();
    
        // uninstallation successful
        return true;
    }
    
    /**
     * Build array with all entity classes for SurveyManager.
     *
     * @return array list of class names.
     */
    protected function listEntityClasses()
    {
        $classNames = array();
        $classNames[] = 'SurveyManager_Entity_Survey';
        $classNames[] = 'SurveyManager_Entity_Page';
        $classNames[] = 'SurveyManager_Entity_Question';
        $classNames[] = 'SurveyManager_Entity_Response';
        $classNames[] = 'SurveyManager_Entity_ResponseData';
    
        return $classNames;
    }
    
    /**
     * Create the default data for SurveyManager.
     *
     * @param array $categoryRegistryIdsPerEntity List of category registry ids.
     *
     * @return void
     */
    protected function createDefaultData($categoryRegistryIdsPerEntity)
    {
        $entityClass = 'SurveyManager_Entity_Survey';
        $this->entityManager->getRepository($entityClass)->truncateTable();
        $entityClass = 'SurveyManager_Entity_Page';
        $this->entityManager->getRepository($entityClass)->truncateTable();
        $entityClass = 'SurveyManager_Entity_Question';
        $this->entityManager->getRepository($entityClass)->truncateTable();
        $entityClass = 'SurveyManager_Entity_Response';
        $this->entityManager->getRepository($entityClass)->truncateTable();
        $entityClass = 'SurveyManager_Entity_ResponseData';
        $this->entityManager->getRepository($entityClass)->truncateTable();
    }
    
    /**
     * Register persistent event handlers.
     * These are listeners for external events of the core and other modules.
     */
    protected function registerPersistentEventHandlers()
    {
        // core -> 
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'api.method_not_found', array('SurveyManager_Listener_Core', 'apiMethodNotFound'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'core.preinit', array('SurveyManager_Listener_Core', 'preInit'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'core.init', array('SurveyManager_Listener_Core', 'init'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'core.postinit', array('SurveyManager_Listener_Core', 'postInit'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'controller.method_not_found', array('SurveyManager_Listener_Core', 'controllerMethodNotFound'));
    
        // front controller -> SurveyManager_Listener_FrontController
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'frontcontroller.predispatch', array('SurveyManager_Listener_FrontController', 'preDispatch'));
    
        // installer -> SurveyManager_Listener_Installer
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'installer.module.installed', array('SurveyManager_Listener_Installer', 'moduleInstalled'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'installer.module.upgraded', array('SurveyManager_Listener_Installer', 'moduleUpgraded'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'installer.module.uninstalled', array('SurveyManager_Listener_Installer', 'moduleUninstalled'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'installer.subscriberarea.uninstalled', array('SurveyManager_Listener_Installer', 'subscriberAreaUninstalled'));
    
        // modules -> SurveyManager_Listener_ModuleDispatch
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'module_dispatch.postloadgeneric', array('SurveyManager_Listener_ModuleDispatch', 'postLoadGeneric'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'module_dispatch.preexecute', array('SurveyManager_Listener_ModuleDispatch', 'preExecute'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'module_dispatch.postexecute', array('SurveyManager_Listener_ModuleDispatch', 'postExecute'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'module_dispatch.custom_classname', array('SurveyManager_Listener_ModuleDispatch', 'customClassname'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'module_dispatch.service_links', array('SurveyManager_Listener_ModuleDispatch', 'serviceLinks'));
    
        // mailer -> SurveyManager_Listener_Mailer
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'module.mailer.api.sendmessage', array('SurveyManager_Listener_Mailer', 'sendMessage'));
    
        // page -> SurveyManager_Listener_Page
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'pageutil.addvar_filter', array('SurveyManager_Listener_Page', 'pageutilAddvarFilter'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'system.outputfilter', array('SurveyManager_Listener_Page', 'systemOutputfilter'));
    
        // errors -> SurveyManager_Listener_Errors
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'setup.errorreporting', array('SurveyManager_Listener_Errors', 'setupErrorReporting'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'systemerror', array('SurveyManager_Listener_Errors', 'systemError'));
    
        // theme -> SurveyManager_Listener_Theme
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'theme.preinit', array('SurveyManager_Listener_Theme', 'preInit'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'theme.init', array('SurveyManager_Listener_Theme', 'init'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'theme.load_config', array('SurveyManager_Listener_Theme', 'loadConfig'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'theme.prefetch', array('SurveyManager_Listener_Theme', 'preFetch'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'theme.postfetch', array('SurveyManager_Listener_Theme', 'postFetch'));
    
        // view -> SurveyManager_Listener_View
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'view.init', array('SurveyManager_Listener_View', 'init'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'view.postfetch', array('SurveyManager_Listener_View', 'postFetch'));
    
        // user login -> SurveyManager_Listener_UserLogin
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'module.users.ui.login.started', array('SurveyManager_Listener_UserLogin', 'started'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'module.users.ui.login.veto', array('SurveyManager_Listener_UserLogin', 'veto'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'module.users.ui.login.succeeded', array('SurveyManager_Listener_UserLogin', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'module.users.ui.login.failed', array('SurveyManager_Listener_UserLogin', 'failed'));
    
        // user logout -> SurveyManager_Listener_UserLogout
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'module.users.ui.logout.succeeded', array('SurveyManager_Listener_UserLogout', 'succeeded'));
    
        // user -> SurveyManager_Listener_User
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'user.gettheme', array('SurveyManager_Listener_User', 'getTheme'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'user.account.create', array('SurveyManager_Listener_User', 'create'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'user.account.update', array('SurveyManager_Listener_User', 'update'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'user.account.delete', array('SurveyManager_Listener_User', 'delete'));
    
        // registration -> SurveyManager_Listener_UserRegistration
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'module.users.ui.registration.started', array('SurveyManager_Listener_UserRegistration', 'started'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'module.users.ui.registration.succeeded', array('SurveyManager_Listener_UserRegistration', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'module.users.ui.registration.failed', array('SurveyManager_Listener_UserRegistration', 'failed'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'user.registration.create', array('SurveyManager_Listener_UserRegistration', 'create'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'user.registration.update', array('SurveyManager_Listener_UserRegistration', 'update'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'user.registration.delete', array('SurveyManager_Listener_UserRegistration', 'delete'));
    
        // users module -> SurveyManager_Listener_Users
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'module.users.config.updated', array('SurveyManager_Listener_Users', 'configUpdated'));
    
        // group -> SurveyManager_Listener_Group
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'group.create', array('SurveyManager_Listener_Group', 'create'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'group.update', array('SurveyManager_Listener_Group', 'update'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'group.delete', array('SurveyManager_Listener_Group', 'delete'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'group.adduser', array('SurveyManager_Listener_Group', 'addUser'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'group.removeuser', array('SurveyManager_Listener_Group', 'removeUser'));
    
        // special purposes and 3rd party api support -> SurveyManager_Listener_ThirdParty
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'get.pending_content', array('SurveyManager_Listener_ThirdParty', 'pendingContentListener'));
        EventUtil::registerPersistentModuleHandler('SurveyManager', 'module.content.gettypes', array('SurveyManager_Listener_ThirdParty', 'contentGetTypes'));
    }
}
