<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Tue Aug 21 20:13:15 CEST 2012.
 */

/**
 * Account api implementation class.
 */
class SurveyManager_Api_Account extends SurveyManager_Api_Base_Account
{
    /**
     * Return an array of items to show in the your account panel.
     *
     * @param array $args List of arguments.
     *
     * @return array List of collected account items
     */
    public function getall($args)
    {
        // collect items in an array
        $items = array();

        // the items below are not needed yet
        // therefore we return an empty list
        return $items;

        $objectType = 'survey';
        $component = $this->name . ':' . ucwords($objectType) . ':';
        $mayAdmin = SecurityUtil::checkPermission($component, '::', ACCESS_ADMIN);
        $mayAdd = SecurityUtil::checkPermission($component, '::', ACCESS_ADD);
        $mayComment = SecurityUtil::checkPermission($component, '::', ACCESS_COMMENT);

        if (!$mayAdmin && $mayAdd) {
            // Teacher
            $icon = 'mytests.png';
            $hasNewContent = false;/** TODO */
            if ($hasNewContent == true) {
                $icon = 'mytests_red.png';
            }
            $items[] = array(
                    'url' => ModUtil::url($this->name, 'user', 'view', array('ot' => $objectType, 'own' => 1)),
                    'title'   => $this->__('Create/View Tests'),
                    'icon'    => $icon,
                    'module'  => $this->name
            );
        } elseif (!$mayComment) {
            // Student
            $icon = 'mytests.png';
            // determine if a Project is at a particular workflow state and a student's test doesn't yet exist
            $hasAssignedTests = false;/** TODO */
            // use the metadata fields in SurveyManager to identify surveys with Classes (or teams or projects).
            // The query needs to:
            //   - consider the workflow status of a Class
            //   - look for related "tests" in SM
            //   - check to see if the given user has taken that test
            if ($hasAssignedTests == true) {
                $icon = 'mytests_red.png';
            }
            $items[] = array(
                    'url' => ModUtil::url($this->name, 'user', 'view', array('ot' => $objectType, 'own' => 1)),
                    'title'   => $this->__('Take Tests'),
                    'icon'    => $icon,
                    'module'  => $this->name
            );
        }

        // return the items
        return $items;
    }
}
