<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Tue Aug 21 20:13:14 CEST 2012.
 */

/**
 * This is the Admin api helper class.
 */
class SurveyManager_Api_Admin extends SurveyManager_Api_Base_Admin
{
    /**
     * Returns available admin panel links.
     *
     * @return array Array of admin links.
     */
    public function getlinks()
    {
        $links = parent::getlinks();
        $configLink = null;

        $allowedMenuEntries = array($this->__('Frontend'));
        if (SecurityUtil::checkPermission($this->name . '::RestrictedAdmin', '::', ACCESS_ADMIN)) {
            $allowedMenuEntries[] = $this->__('Surveys');
        }
        $canAdminResponses = SecurityUtil::checkPermission($this->name . '::Response', '::', ACCESS_ADMIN);
        if ($canAdminResponses) {
            $allowedMenuEntries[] = $this->__('Responses');
        }
        if (SecurityUtil::checkPermission($this->name . '::Config', '::', ACCESS_ADMIN)) {
            $allowedMenuEntries[] = $this->__('Configuration');
        }

        foreach ($links as $k => $v) {
            if (in_array($v['text'], $allowedMenuEntries)) {
                if ($v['text'] == $this->__('Configuration')) {
                    $configLink = $v;
                }
                continue;
            }
            unset($links[$k]);
        }

        if ($canAdminResponses && $this->getVar('useFeaturedResponses', false)) {
            if ($configLink != null) {
                array_pop($links);
            }
            $links[] = array('url' => ModUtil::url($this->name, 'admin', 'featured'),
                             'text' => $this->__('Featured Responses'),
                             'title' => $this->__('Manage featured responses'));
            if ($configLink != null) {
                $links[] = $configLink;
            }
        }

        return $links;
    }
}
