<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Thu Aug 30 15:09:35 CEST 2012.
 */

/**
 * This is the User api helper class.
 */
class SurveyManager_Api_User extends SurveyManager_Api_Base_User
{
    /**
     * Returns available user panel links.
     *
     * @return array Array of user links.
     */
    public function getlinks()
    {
        $links = array();
        return $links;
    }
}