<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * This class provides object meta data for the Tag module.
 */
class SurveyManager_TaggedObjectMeta_SurveyManager extends SurveyManager_TaggedObjectMeta_Base_SurveyManager
{
    // feel free to extend the tag support here
}
