<?php
/**
 * SurveyManager.
 *
 * @copyright Zikula Development Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SurveyManager
 * @author Zikula Development Team <info@zikula.org>.
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * This handler class handles the page events of the Form called by the surveyManager_admin_edit() function.
 * It aims on the response data object type.
 */
class SurveyManager_Form_Handler_Admin_ResponseData_Edit extends SurveyManager_Form_Handler_Admin_ResponseData_Base_Edit
{
    // feel free to extend the base handler class here
}
